// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: session.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace RTC.ProtoGrpc.SessionServer {
  public static partial class SessionService
  {
    static readonly string __ServiceName = "RTC.ProtoGrpc.SessionServer.SessionService";

    static readonly grpc::Marshaller<global::RTC.ProtoGrpc.SessionServer.O2S_CheckSession> __Marshaller_RTC_ProtoGrpc_SessionServer_O2S_CheckSession = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::RTC.ProtoGrpc.SessionServer.O2S_CheckSession.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::RTC.ProtoGrpc.SessionServer.S2O_CheckSession> __Marshaller_RTC_ProtoGrpc_SessionServer_S2O_CheckSession = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::RTC.ProtoGrpc.SessionServer.S2O_CheckSession.Parser.ParseFrom);

    static readonly grpc::Method<global::RTC.ProtoGrpc.SessionServer.O2S_CheckSession, global::RTC.ProtoGrpc.SessionServer.S2O_CheckSession> __Method_CheckSession = new grpc::Method<global::RTC.ProtoGrpc.SessionServer.O2S_CheckSession, global::RTC.ProtoGrpc.SessionServer.S2O_CheckSession>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CheckSession",
        __Marshaller_RTC_ProtoGrpc_SessionServer_O2S_CheckSession,
        __Marshaller_RTC_ProtoGrpc_SessionServer_S2O_CheckSession);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::RTC.ProtoGrpc.SessionServer.SessionReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SessionService</summary>
    public abstract partial class SessionServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::RTC.ProtoGrpc.SessionServer.S2O_CheckSession> CheckSession(global::RTC.ProtoGrpc.SessionServer.O2S_CheckSession request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SessionService</summary>
    public partial class SessionServiceClient : grpc::ClientBase<SessionServiceClient>
    {
      /// <summary>Creates a new client for SessionService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SessionServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SessionService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SessionServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SessionServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SessionServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::RTC.ProtoGrpc.SessionServer.S2O_CheckSession CheckSession(global::RTC.ProtoGrpc.SessionServer.O2S_CheckSession request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckSession(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::RTC.ProtoGrpc.SessionServer.S2O_CheckSession CheckSession(global::RTC.ProtoGrpc.SessionServer.O2S_CheckSession request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CheckSession, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::RTC.ProtoGrpc.SessionServer.S2O_CheckSession> CheckSessionAsync(global::RTC.ProtoGrpc.SessionServer.O2S_CheckSession request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckSessionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::RTC.ProtoGrpc.SessionServer.S2O_CheckSession> CheckSessionAsync(global::RTC.ProtoGrpc.SessionServer.O2S_CheckSession request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CheckSession, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SessionServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SessionServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SessionServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CheckSession, serviceImpl.CheckSession).Build();
    }

  }
}
#endregion
